apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../templates/argocd/application
namespace: argocd
namePrefix: email-consumer-api-stdv-
commonLabels:
  app.kubernetes.io/name: email-consumer-api
  app.kubernetes.io/namespace: stdv-common-backend
  app.company.io/environment: staging
  app.company.io/team: development
patches:
- patch: |-
    [{"op": "replace", "path": "/spec/destination/namespace", "value": "stdv-common-backend"},
                {"op": "replace", "path": "/spec/project", "value": "common-backend-project"},
                {"op": "replace", "path": "/spec/source/path", "value": "common-backend/environments/staging/email-consumer-api"}]
  target:
    group: argoproj.io
    kind: Application
    name: application
    version: v1alpha1
