apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-hpa
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 95
          type: Utilization
